App\Entity\Animal:
    attributes:
        id:
            groups: [
                "animal:collection:get",
                "animal:item:get",
                "milkyieldrecord:collection:get",
                "milkyieldrecord:item:get",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        name:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        tagId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "milkyieldrecord:collection:get",
                "milkyieldrecord:item:get",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        herdId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        countryId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        regionId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        districtId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        wardId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        villageId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        orgId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        animalType:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        sex:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        birthdate:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        sireType:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        sireId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        sireTagId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        damId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        damTagId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        mainBreed:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        breedComposition:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        animalPhoto:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        latitude:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        longitude:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        mapAddress:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        regDate:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        hairSampleId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        migrationId:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        odkAnimalCode:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        farm:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch",
                "animalevent:collection:get",
                "animalevent:item:get"
            ]
        additionalAttributes:
            groups: [
                "animal:collection:get",
                "animal:collection:post",
                "animal:item:get",
                "animal:item:put",
                "animal:item:patch"
            ]
        createdAt:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        createdBy:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        updatedAt:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        updatedBy:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        lastCalving:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        daysSinceLastCalving:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        milkingEvents:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        lastMilkingEvent:
            groups: [
                "animal:collection:get",
                "animal:item:get"
            ]
        averageMilkYield:
            groups: [
                    "animal:collection:get",
                    "animal:item:get"
            ]
        calvingInterval:
            groups: [
                    "animal:collection:get",
                    "animal:item:get"
            ]
