App\Entity\Herd:
  collectionOperations:
    get:
      method: get
      path: /herds
    post:
      method: post
      path: /herds
      openapi_context:
        description:
          '<h3>Creates a Herd resource</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`countryId`<p>All other properties are **optional**.</p>'
  itemOperations:
    get:
      method: get
      path: /herds/{id}
    put:
      method: put
      path: /herds/{id}
      openapi_context:
        description:
          '<h3>Replaces the Herd resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`isActive`<p>`isDeleted`</p><p>`name`</p><p>All other properties are **optional**.</p>'
    patch:
      method: patch
      path: /herds/{id}
      openapi_context:
        description:
          '<h3>Updates the Herd resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`name`<p>All other properties are **optional**.</p>'
